export interface Paytable {
    
        // standard_ctc: string,
        // gross_pay: string,
        // take_home: string,
        // payable_days: string,
        // paid_days: string,
        // code: string,
        // full_name: string,
        // doj: string,
        // pf_number: string,
        // esi_number: string,
        // entity_id_y: string,
        // employee_id_y: string,
        // amount: string,
        // deduction_status: string,
        // status: string,
        // Annual_bonus_paid_Monthly: string,
        // 'Basic&Da': string,
        // Conveyance: string,
        // LTA: string,
        // MEDICAL: string,
        // Others: string,
        // PF: string,
        // Telephone: string,
        // 'Test Data': string,
        // Dearness: string,
        // House_Rent: string,
        // Special

        "employee_id": 130,
        "Gross pay_std": 30000.0,
        "Std Annual Bonus Paid Monthly": null,
        "Std Basic & DA": 11400.0,
        "Std CmpESI": null,
        "Std CmpPF": null,
        "Std Conveyance": 3000.0,
        "Std HRA": 11400.0,
        "Std LTA": null,
        "Std Medical": 2700.0,
        "Std Others": null,
        "Std Telephone": 1500.0,
        "Gross pay": 8709.68,
        "Annual Bonus Paid Monthly": null,
        "Basic & DA": 3309.68,
        "Cmpy contStd CmpESI": null,
        "Cmpy contStd CmpPF": null,
        "Conveyance": 870.97,
        "Extra Allowance": null,
        "HRA": 3309.68,
        "LTA": null,
        "Medical": 783.87,
        "Others": null,
        "Telephone": 435.48,
        "id": 130,
        "full_name": "SARAVANAN L",
        "code": "VS0280",
        "employee_branch__code": "101",
        "employee_branch__name": "Chennai Head Office",
        "doj": null
    
}
